PREPROCESS_OUTPUT_PATH = "annotations.json"

TRANSLATION_OUTPUT_PATH = "annotations_translated.json"
TRANSLATION_MAX_LENGTH = 1024
TRANSLATION_OUTPUT_LENGTH_MULTIPLIER = 1.5
TRANSLATION_BATCH_SIZE = 64
